import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync } from "fs";

const production = process.argv[2] === "production";

// Dev builds go straight into the dev vault so the plugin can be reloaded
// in Obsidian without a manual copy step. Production builds go to dist/.
const outdir = production ? "dist" : "dev-vault/.obsidian/plugins/mindmap-view";
mkdirSync(outdir, { recursive: true });

const context = await esbuild.context({
	banner: {
		js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD. If you want to view the source, visit the github repository of this plugin */",
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: production ? false : "inline",
	treeShaking: true,
	outfile: `${outdir}/main.js`,
	minify: production,
});

copyFileSync("manifest.json", `${outdir}/manifest.json`);
copyFileSync("styles.css", `${outdir}/styles.css`);

if (production) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
