#!/usr/bin/env node
// Cross-platform (Windows/macOS/Linux) output-path resolution for
// generate-mindmap. Node's `path`/`fs` APIs abstract path separators and
// filesystem calls, so this avoids any OS-specific shell commands
// (mkdir -p, cp, etc.) that behave differently across platforms.
//
// Usage:
//   node resolve-output.mjs <input-file...> [--output <name>] [--output-dir <dir>]
//
// Prints the final absolute output path to stdout (nothing else), and
// creates the output directory if it doesn't exist yet. Exits non-zero
// with a message on stderr if an input file is missing.

import fs from "node:fs";
import path from "node:path";

function parseArgs(argv) {
	const args = { inputs: [], output: null, outputDir: null };
	for (let i = 0; i < argv.length; i++) {
		const a = argv[i];
		if (a === "--output") args.output = argv[++i];
		else if (a === "--output-dir") args.outputDir = argv[++i];
		else args.inputs.push(a);
	}
	return args;
}

function ensureMdExt(name) {
	return /\.md$/i.test(name) ? name : `${name}.md`;
}

function timestamp() {
	return new Date().toISOString().replace(/[:T]/g, "-").replace(/\..+/, "");
}

/** A generation-time default name — Claude should usually pass an explicit --output with a name derived from the actual content instead of relying on this. */
function defaultBaseName(inputs) {
	if (inputs.length === 1) return `${path.basename(inputs[0], path.extname(inputs[0]))}-mindmap`;
	return `combined-mindmap-${timestamp()}`;
}

/** Appends -2, -3, ... until the path doesn't collide. Only used for auto-generated names — an explicit --output is respected as-is (the caller chose it deliberately). */
function uniquePath(p) {
	if (!fs.existsSync(p)) return p;
	const dir = path.dirname(p);
	const ext = path.extname(p);
	const base = path.basename(p, ext);
	let n = 2;
	let candidate;
	do {
		candidate = path.join(dir, `${base}-${n}${ext}`);
		n++;
	} while (fs.existsSync(candidate));
	return candidate;
}

const args = parseArgs(process.argv.slice(2));
if (args.inputs.length === 0) {
	console.error("Usage: resolve-output.mjs <input-file...> [--output <name>] [--output-dir <dir>]");
	process.exit(1);
}
for (const input of args.inputs) {
	if (!fs.existsSync(input)) {
		console.error(`Input file not found: ${input}`);
		process.exit(1);
	}
}

const outputDir = path.resolve(args.outputDir ?? path.dirname(path.resolve(args.inputs[0])));
fs.mkdirSync(outputDir, { recursive: true });

const isAutoGenerated = !args.output;
const outputName = ensureMdExt(args.output ?? defaultBaseName(args.inputs));
let finalPath = path.join(outputDir, outputName);
if (isAutoGenerated) finalPath = uniquePath(finalPath);

console.log(finalPath);
